name: Protect Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from `development`
        run: |
          if [[ "${{ github.head_ref }}" != "development" ]]; then
            echo "Pull requests to 'main' are only allowed from 'development'."
            exit 1
          fi
